docs: fix README file
openshift/aws-account-shredder pull request #70
Opened 2022-04-21 10:12 UTC by shibumi

This fixes a little typo in the README + adds a better explanation for the access env variables

2022-04-21 10:44 UTC, fahlmant commented on README.md
> +AWS_ACCESS_KEY_ID           # IAM account that has permission to shred the accounts
This description is not quite accurate; This var holds the Access Key ID of an Access Key pair.

2022-04-21 10:44 UTC, fahlmant commented on README.md
> +AWS_SECRET_ACCESS_KEY       # Secret key for the IAM account above
```suggestion
AWS_SECRET_ACCESS_KEY       # Secret key for the access key pair
```

2022-04-21 10:45 UTC, fahlmant commented on README.md
> +AWS_ACCESS_KEY_ID           # IAM account that has permission to shred the accounts
For more information, here are the docs around Access Keys https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html

2022-04-21 10:46 UTC, fahlmant requested changes
Comment changes are not quite accurate

2022-08-23 09:16 UTC, dastergon commented
@fahlmant would you mind pushing your recommendations and merging? Christian is no longer working at RH.

2022-08-23 11:24 UTC, fahlmant commented
This repo is not under active development anymore, and should be archived soon. I'm going to instead close this.

2022-08-23 11:24 UTC, closed without merging